; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CA24C289-371B-4FB4-9492-C5AB77F325D3}
AppName=CMX
AppVersion=3.0
;AppVerName=CMX 3.0
AppPublisher=Cheat Matrix
AppPublisherURL=http://www.cheatmatrix.com.br
AppSupportURL=http://www.cheatmatrix.com.br
AppUpdatesURL=http://www.cheatmatrix.com.br
DefaultDirName={pf}\CMX
DefaultGroupName=CMX
OutputDir=C:\CMX\Setup
OutputBaseFilename=setup
SetupIconFile=C:\Projetos\Cheating_Matrix\cmx2.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\cmx.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\cmg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\matriz.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\msvcrt36.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\reload.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\Plugins\*"; DestDir: "{app}\Plugins\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\Updates\*"; DestDir: "{app}\Updates\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Projetos\Cheating_Matrix\Compiled\Publish\Screenshots\*"; DestDir: "{app}\Screenshots\"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\CMX"; Filename: "{app}\cmx.exe"; WorkingDir: "{app}"
Name: "{group}\{cm:ProgramOnTheWeb,CMX}"; Filename: "http://www.cheatmatrix.com.br"
Name: "{group}\{cm:UninstallProgram,CMX}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\CMX"; Filename: "{app}\cmx.exe"; Tasks: desktopicon; WorkingDir: "{app}"
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\CMX"; Filename: "{app}\cmx.exe"; Tasks: quicklaunchicon; WorkingDir: "{app}"

[Run]
Filename: "{app}\cmx.exe"; Description: "{cm:LaunchProgram,CMX}"; Flags: nowait postinstall skipifsilent

