PCRE Support for Borland VCL
----------------------------

Robert Dunn's home pages is http://home.att.net/~robertdunn/Yacs.html. Here you 
will find links to his port of PCRE. This is what the home page says about it:

  New Code:  Regular Expression Searches
  
  After some lengthy effort, I have developed a light-weight class to
  implement regular expression searches for TRichEdit components.  See the
  Code Samples section for the TTaeRegExp class.  If you do not know what
  "regular expressions" are, check out the Regular Expression Syntax.page.
  (Note: This code "upgrades" the BCB/VCL from PCRE 2.x to PCRE 3.4.)

